# Generated by Django 4.2.18 on 2025-03-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0002_delete_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComedPriceData',
            fields=[
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False, unique=True)),
                ('price', models.FloatField(default=0.0)),
            ],
        ),
    ]
