# Generated by Django 4.2.18 on 2025-04-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_ubibotsensortemp'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatteryData',
            fields=[
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False, unique=True)),
                ('percent', models.FloatField(default=-1)),
            ],
        ),
    ]
