# Generated by Django 4.2.18 on 2025-02-13 21:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='NewGenericDevice', max_length=100, null=True)),
                ('type', models.CharField(choices=[('generic', 'Generic Device'), ('kasa_switch', 'Kasa Switch'), ('fridge', 'Fridge')], default='generic', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fridge',
            fields=[
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='devices.device')),
                ('high_temp_threshold', models.FloatField(default=50.0)),
                ('low_temp_threshold', models.FloatField(default=20.0)),
                ('target_temp_threshold', models.FloatField(default=38.0)),
            ],
        ),
        migrations.CreateModel(
            name='KasaSwitch',
            fields=[
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='devices.device')),
                ('ip_address', models.GenericIPAddressField()),
            ],
        ),
    ]
