# Generated by Django 4.2.18 on 2025-03-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_remove_energyconsumption_device_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyconsumption',
            name='timestamp',
            field=models.DateTimeField(default=None),
        ),
    ]
