# Generated by Django 4.2.18 on 2025-03-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_alter_energyconsumption_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='off_window_begin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='off_window_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='on_window_begin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='on_window_end',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
