# Generated by Django 4.2.18 on 2025-03-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_device_off_window_begin_device_off_window_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='critical_load',
            field=models.BooleanField(default=False),
        ),
    ]
