# Generated by Django 4.2.18 on 2025-03-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_device_critical_load'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='adr_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
